### ISSUE TITLE
no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"

### ISSUE THREAD

**Issue by hillbun** [cnrancher/octopus#122]
kubectl apply -f https://raw.githubusercontent.com/cnrancher/octopus/master/deploy/e2e/all_in_one.yaml

```
namespace/octopus-system created
role.rbac.authorization.k8s.io/octopus-leader-election-role created
clusterrole.rbac.authorization.k8s.io/octopus-manager-role created
rolebinding.rbac.authorization.k8s.io/octopus-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/octopus-manager-rolebinding created
service/octopus-brain created
service/octopus-limb created
deployment.apps/octopus-brain created
daemonset.apps/octopus-limb created
error: unable to recognize "https://raw.githubusercontent.com/cnrancher/octopus/master/deploy/e2e/all_in_one.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

kubernetes v1.15.6

**Comment by thxCode** [comment]
@hillbun , please retry via Kubernetes which supports `apiextensions.k8s.io/v1` API, Octopus currently has no plans to support the previous versions. Octopus provides a quick-start script to bring up a local K3s cluster via K3d, maybe you can have a taste: `curl -fL https://octopus-assets.oss-cn-beijing.aliyuncs.com/k3d/cluster-k3s-spinup.sh | bash -`. You can view more details from https://cnrancher.github.io/docs-octopus. 

I will close this issue, please reopen it if needed, have a good day with Octopus.
