### ISSUE TITLE
How to access Octopus-UI?

### ISSUE THREAD

**Issue by hillbun** [cnrancher/octopus#123]
what's username and password?

I install with 
kubectl apply -f https://raw.githubusercontent.com/cnrancher/octopus-api-server/master/deploy/e2e/all_in_one.yaml

```
kubectl get svc -n kube-system -l app.kubernetes.io/name=octopus-ui
NAME         TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
octopus-ui   NodePort   10.106.214.157   <none>        8443:8899/TCP   19m
```

nodeport exposed

**Comment by thxCode** [comment]
@hillbun , Ocotpus UI is a special UI for K3s, after brought up a K3s cluster, you can find the account in the KUBECONFIG file. https://cnrancher.github.io/docs-octopus/docs/en/octopus-ui#authentication.

I will close this issue, please reopen it if needed, have a good day with Octopus.

**Comment by hillbun** [comment]
@thxCode 

is it possible to install it on k3s single node?

**Comment by thxCode** [comment]
@hillbun yes, it should be possible to deploy to k3s single node, which has master and agent role.

**Comment by 1000sprites** [comment]
k3s kubectl get svc -n kube-system -l app.kubernetes.io/name=octopus-ui

NAME                 TYPE           CLUSTER-IP     EXTERNAL-IP       PORT(S)          AGE
octopus-octopus-ui   LoadBalancer   10.43.104.46   192.168.153.129   8443:31210/TCP   45h
octopus-ui           LoadBalancer   10.43.74.89    <pending>         8443:31451/TCP   5m33s

can't access the octopus-ui, how to solve it?

**Comment by 1000sprites** [comment]
k3s kubectl get svc -n kube-system -l app.kubernetes.io/name=octopus-ui

`
root@k3s1:/home/ubuntu# k3s kubectl get svc -n kube-system -l app.kubernetes.io/name=octopus-ui
NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)          AGE
octopus-octopus-ui   LoadBalancer   10.43.104.46    192.168.153.129   8443:31210/TCP   2d1h
myapp-octopus-ui     LoadBalancer   10.43.126.154   <pending>         8443:31044/TCP   7m46s
`

can't access the octopus-ui, how to solve it?

**Comment by 1000sprites** [comment]
k3s kubectl get svc -n kube-system -l app.kubernetes.io/name=octopus-ui

```
root@k3s1:/home/ubuntu# k3s kubectl get svc -n kube-system -l app.kubernetes.io/name=octopus-ui
NAME                 TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)          AGE
octopus-octopus-ui   LoadBalancer   10.43.104.46    192.168.153.129   8443:31210/TCP   2d1h
myapp-octopus-ui     LoadBalancer   10.43.126.154   <pending>         8443:31044/TCP   7m46s
```
can't access the octopus-ui, how to solve it?
