### ISSUE TITLE
Possible channel duplicate close problem

### ISSUE THREAD

**Issue by shouhong** [cnrancher/octopus#133]
**Environment information:**

- Octopus version : master
- Installer : *

**Cluster information:**

- Cluster vendor : k3s
- Machine type : vm
- Kubernetes version (use `kubectl version`): 1.18
- Docker version (use `docker version`): 19.03.9

**Machine specification:**

| Role | Number | Specification (CPU/RAM) |
|:---:|:---:|:---:|
|  master | 1 | 4U8G |
| agent | 3 | 4U8G | 

**Steps to reproduce (least amount of steps as possible):**

1. In source file adaptors/dummy/pkg/physical/device_special.go, there are codes like below
```
...
func (d *specialDevice) stopMock() {
	if d.stop != nil {
		close(d.stop)
		d.stop = nil
	}
}
...
```
The stop channel may be closed twice which causes panic if stopMock() function is called concurrently. The are two functions: Shutdown() and refresh(...) call stopMock() function.
2. The same problem exists for all adaptors(ble, modbus, dummy and opcua)

**Result:** The stopMock function may not work in some situations.

**Other details that may be helpful:**

**Except:** The stopMock function should always work as expected.

**Related Issues:**

**Comment by thxCode** [comment]
@shouhong , hey, thanks for the report. We just pass the stop channel handler to any select blocks, so `d.stop=nil` will not affect the passed handler.

**Comment by shouhong** [comment]
@thxCode Thanks for your review. You are right, the `d.stop=nil` is not a problem. But the stop channel has the possibility to be closed twice which will cause panic. I have updated the issue description. Can you please help review again?

**Comment by thxCode** [comment]
Ya, @shouhong , I confirmed the code again, we have already used a mutex to lock any stop operations, so I don't think the channel will be closed twice.

**Comment by shouhong** [comment]
@thxCode That's fine! I will close this issue and corresponding PR.
