### ISSUE TITLE
The Namespace value is assgined to Name

### ISSUE THREAD

**Issue by shouhong** [cnrancher/octopus#135]
**Environment information:**

- Octopus version : master
- Installer : *

**Cluster information:**

- Cluster vendor : k3s
- Machine type : vm
- Kubernetes version (use `kubectl version`): 1.18
- Docker version (use `docker version`): 19.09.13

**Machine specification:**

| Role | Number | Specification (CPU/RAM) |
|:---:|:---:|:---:|
|  master | 1 | 4U8G |
| agent | 3 | 4U8G | 

**Steps to reproduce (least amount of steps as possible):**

1. There are codes to assign Namespace value to Name
```
resp.Name = in.Namespace
```

**Result:** The Namespace value is assgined to Name.

**Other details that may be helpful:** Files with  this problem:
1. adaptors/ble/pkg/adaptor/service.go
2. adaptors/dummy/pkg/adaptor/service.go
3. adaptors/modbus/pkg/adaptor/service.go
4. adaptors/mqtt/pkg/adaptor/service.go
5. adaptors/opcua/pkg/adaptor/service.go

**Except:** Assign the Name value to Name

**Related Issues:**

**Comment by thxCode** [comment]
@shouhong , hey, thanks for the report, I will review the corresponding PR ASAP.

**Comment by thxCode** [comment]
Close as the corresponding PR is merged, this issue doesn't need a regression testing.
