### ISSUE TITLE
How to get the permission to check detail build error logs?

### ISSUE THREAD

**Issue by shouhong** [cnrancher/octopus#137]
**Question:** After submitting a PR, I got "continuous-integration/drone/pr — Build is failing" error. But I don't have the permission to check the details of the error. How to get the permission to check detail build error logs?

**Related Issues:**

**Comment by thxCode** [comment]
Have you tried to connect with Github account?

**Comment by thxCode** [comment]
@shouhong , We have confirmed that you can log into the Drone CI with your Github account and view the CI error report. I will close this issue, thanks.
