### ISSUE TITLE
There is a problem when I install octopus pod in k3s cluster

### ISSUE THREAD

**Issue by ttlv** [cnrancher/octopus#143]
**Question:**
![k3s_issue_image_1](https://user-images.githubusercontent.com/20856105/92191517-93c6b600-ee96-11ea-92bf-2199d7b261a2.jpg)
![k3s_issue_image_3](https://user-images.githubusercontent.com/20856105/92191537-9f19e180-ee96-11ea-9494-1994d75b9613.jpg)
When I use yaml to install octopus manuanlly, everything is ok.the status of octopus-ui pod is running and I use NodePort svc to replace LoadBalancer.K3s Service is a node which has a public ip address,so I can get the octopus page in https://117.51.143.29:30128. but I just get  time out from chrome. When I use netstat -anpt | grep 30128.There absolutely have a tcp connection is listening on 30128 port
![111111](https://user-images.githubusercontent.com/20856105/92191784-3b43e880-ee97-11ea-8a52-ec706e0f504e.jpg)
There are some logs about octopus pod 
![ k3s_issue_image_2 jpg](https://user-images.githubusercontent.com/20856105/92191807-472faa80-ee97-11ea-8c78-74d2498e34ca.jpg)
![22222222222](https://user-images.githubusercontent.com/20856105/92191877-63334c00-ee97-11ea-8bca-5ef90fd0c4f7.jpg)

What's more,the pod of coredns is running normally and the svc of k3s cluster is already existed so the content of log makes me feel very confused。

**Comment by thxCode** [comment]
Perhaps you can try this: https://docs.rancher.cn/docs/octopus/faq/_index/#%E6%98%AF%E5%90%A6%E6%94%AF%E6%8C%81%E6%9C%AC%E5%9C%B0%E7%A6%BB%E7%BA%BF%E8%AE%BF%E9%97%AE-ui%EF%BC%9F (Chinese), https://cnrancher.github.io/docs-octopus/docs/en/faq#does-it-support-local-offline-access-to-ui (English).

**Comment by ttlv** [comment]
well, thanks for your suggestion,I found that core-dns port is not ready, I restarted my k3s cluster,now I have resolved this problem,everything is ok.
